### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by Zeffut** [helmi77/youtube-checker#1]
Hello, the scrypt give me that error. I don't undertand why :

```
Traceback (most recent call last):
  File "c:\Users\Moi\Downloads\youtube-checker-master\youtube-checker-master\checker.py", line 107, in <module>
    main()
  File "c:\Users\Moi\Downloads\youtube-checker-master\youtube-checker-master\checker.py", line 59, in main
    channel = youtube.get_channel_by_username(args.username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Moi\Downloads\youtube-checker-master\youtube-checker-master\youtubeapi.py", line 82, in get_channel_by_username
    channel = self.channel_from_response(channels_response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Moi\Downloads\youtube-checker-master\youtube-checker-master\youtubeapi.py", line 47, in channel_from_response
    for channel in response['items']:
                   ~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

**Comment by Zeffut** [comment]
I try with another channel and this work so i think the scrypt don't work with the channel of big Youtuber. Any solutions ?

**Comment by Zeffut** [comment]
Finaly only work with the channel LastWeekTonight....

**Comment by wolfsblu** [comment]
Pushed a new commit that should resolve the issue
